---
# Deploy a VM from a ISO using Ansible 'vmware_guest' module
- name: Deploy VM from iso
  vmware_guest:
    hostname: '{{ deploy_vCenter_host }}'
    username: '{{ deploy_vCenter_user }}'
    password: '{{ deploy_vCenter_password }}'
    validate_certs: no
    datacenter: '{{ deploy_vCenter_datacenter }}'
    esxi_hostname: "{{ deploy_vCenter_esxhost }}"
    #cluster: '{{ deploy_vsphere_cluster }}'
    #resource_pool: '{{ deploy_vsphere_resourcepool }}'
    folder: '{{ deploy_vCenter_folder }}'
    name: '{{ inventory_hostname }}'
    state: poweredon
    #template: OS_Ubuntu_14_template
    annotation: "{{ guest_notes }}"
    guest_id: ubuntu64guest
    disk:
    - size_gb: "{{ guest_disk_size | default(80) }}"
      type: thin
      datastore: '{{ deploy_vCenter_datastore }}'
    networks:
    - name: VM Network
      device_type: vmxnet3
      start_connected: True
     #wait_for_ip_address: true
    hardware:
      memory_mb: "{{ vm_memory | default(8192) }}"
      num_cpus: "{{ vm_cpu | default(8) }}"
    cdrom:
      controller_number: 0
      unit_number: 0
      #state: present
      type: iso
      iso_path: "[datastore18_2] test_ansi_OS_ISO/ubuntu-16.04.7-server-amd64.iso"
    wait_for_ip_address: true
  delegate_to: localhost
  register: newvm 
 
- name: IP address of Virtual Machine 
  debug:
    msg: "ip address of VM is : {{ newvm.instance.ipv4 }} "
